//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCR.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
    	public int MemberId { get; set; }
    	public string FirstName { get; set; }
    	public string LastName { get; set; }
    	public bool IsActive { get; set; }
    	public int MemberSince { get; set; }
    	public string Bio { get; set; }
    	public string Photo { get; set; }
    	public System.DateTime CreatedOn { get; set; }
    	public int CreatedBy { get; set; }
    	public System.DateTime ModifiedOn { get; set; }
    	public int ModifiedBy { get; set; }
    }
}
