//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCR.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Season
    {
    	public Season()
    	{
    		this.Schedules = new HashSet<Schedule>();
    	}
    
    	public int SeasonId { get; set; }
    	public string SeasonName { get; set; }
    	public System.DateTime StartDate { get; set; }
    	public System.DateTime EndDate { get; set; }
    	public System.DateTime CreatedOn { get; set; }
    	public int CreatedBy { get; set; }
    	public System.DateTime ModifiedOn { get; set; }
    	public int ModifiedBy { get; set; }
    
    	public virtual ICollection<Schedule> Schedules { get; set; }
    }
}
