//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCR.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
    	public Team()
    	{
    		this.Schedules = new HashSet<Schedule>();
    	}
    
    	public int TeamId { get; set; }
    	public string TeamName { get; set; }
    	public string Location { get; set; }
    	public bool IsActive { get; set; }
    	public bool IsSelf { get; set; }
    	public System.DateTime CreatedOn { get; set; }
    	public int CreatedBy { get; set; }
    	public System.DateTime ModifiedOn { get; set; }
    	public int ModifiedBy { get; set; }
    
    	public virtual ICollection<Schedule> Schedules { get; set; }
    }
}
