//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCR.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSetting
    {
    	public int UserSettingId { get; set; }
    	public int UserId { get; set; }
    	public string SettingName { get; set; }
    	public string SettingValue { get; set; }
    	public int ValueTypeCode { get; set; }
    	public System.DateTime CreatedOn { get; set; }
    	public int CreatedBy { get; set; }
    	public System.DateTime ModifiedOn { get; set; }
    	public int ModifiedBy { get; set; }
    
    	public virtual UserProfile UserProfile { get; set; }
    }
}
