//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCR.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using GCR.Core.Entities;
    
    internal partial class DB : DbContext
    {
    	protected void OnConstructorCalled()
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AppSetting> AppSettings { get; set; }
        public DbSet<HomePagePhoto> HomePagePhotoes { get; set; }
        public DbSet<Member> Members { get; set; }
        public DbSet<News> News { get; set; }
        public DbSet<Schedule> Schedules { get; set; }
        public DbSet<Season> Seasons { get; set; }
        public DbSet<Team> Teams { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<UserSetting> UserSettings { get; set; }
    }
}
